# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONnMqimo_kmYmOVT5GFp6QOzlt5t-w62
"""

!nvidia-smi

import torch
import torchvision
print("PyTorch version:", torch.__version__)
print("Torchvision version:", torchvision.__version__)
print("CUDA is available:", torch.cuda.is_available())
import sys

!pip install streamlit
!pip install ngrok
!pip install tensorrt

!pip install streamlit-lottie

import os
HOME = os.getcwd()

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!git clone https://github.com/IDEA-Research/GroundingDINO.git
# %cd {HOME}/GroundingDINO
!pip install -q -e .
#!pip install -q roboflow

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!mkdir -p /drive
#umount /drive
!mount --bind /content/drive/My\ Drive /drive
!mkdir -p /drive/ngrok-ssh
!mkdir -p ~/.ssh

#%cd {HOME}/GroundingDINO
#loading grounding dino into memory

!apt-get install ssh tmux vim

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ~/.ssh/authorized_keys
# REPLACE_THIS_LINE_WITH_YOUR_ID_RSA_PUB_FILE

!cp /drive/ngrok-ssh/sshd_config /etc/ssh/sshd_config
!service ssh restart
!mkdir -p ~/.ssh

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /drive/ngrok-ssh
# %cd /drive/ngrok-ssh
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok-stable-linux-amd64.zip
!unzip -u ngrok-stable-linux-amd64.zip
!cp /drive/ngrok-ssh/ngrok /ngrok
!chmod +x /ngrok

!/ngrok authtoken 2OGUhaFy7XKfmGHWNSjRcKh6Cii_5aEoYAr683EXM8aR2qBPQ

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /drive/ngrok-ssh/http8080.yml
# tunnels:
#   http8080:
#     proto: http
#     addr: 8501
#     inspect: false
#     bind_tls: true

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /drive/ngrok-ssh/run_ngrok.sh
# #!/bin/sh
# set -x
# /ngrok start --config /drive/ngrok-ssh/http8080.yml "$@"

!streamlit run /drive/ngrok-ssh/app.py & npx localtunnel --port 8501 --server.gatherUsageStats False

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gpu_usage.sh
# #! /bin/bash
# #comment: run for 10 seconds, change it as per your use
# end=$((SECONDS+10))
# 
# while [ $SECONDS -lt $end ]; do
#     nvidia-smi --format=csv --query-gpu=power.draw,utilization.gpu,memory.used,memory.free,fan.speed,temperature.gpu >> gpu.log
#     #comment: or use below command and comment above using #
#     #nvidia-smi dmon -i 0 -s mu -d 1 -o TD >> gpu.log
# done

